=== TestGit221994/com.demo.cucumber.api/target/test-classes/Schema/Response/SchemaOfRequestBody_Activities_POST_API.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "default": {},
  "title": "Root Schema",
  "required": [
    "id",
    "title",
    "dueDate",
    "completed"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "default": 0,
      "title": "The id Schema",
      "examples": [
        2
      ]
    },
    "title": {
      "type": "string",
      "default": "",
      "title": "The title Schema",
      "examples": [
        "AavBsCdTL"
      ]
    },
    "dueDate": {
      "type": "string",
      "default": "",
      "title": "The dueDate Schema",
      "examples": [
        "2023-04-09T11:39:04.146Z"
      ]
    },
    "completed": {
      "type": "boolean",
      "default": false,
      "title": "The completed Schema",
      "examples": [
        true
      ]
    }
  },
  "examples": [{
    "id": 2,
    "title": "AavBsCdTL",
    "dueDate": "2023-04-09T11:39:04.146Z",
    "completed": true
  }]
}

=== TestGit221994/com.demo.cucumber.api/target/test-classes/ResponseBody/apiResponseBodyOf_Activities GET API.json
[
    {
        "id": 1,
        "title": "Activity 1",
        "dueDate": "2023-07-29T12:04:18.1410449+00:00",
        "completed": false
    },
    {
        "id": 2,
        "title": "Activity 2",
        "dueDate": "2023-07-29T13:04:18.1410474+00:00",
        "completed": true
    },
    {
        "id": 3,
        "title": "Activity 3",
        "dueDate": "2023-07-29T14:04:18.1410478+00:00",
        "completed": false
    },
    {
        "id": 4,
        "title": "Activity 4",
        "dueDate": "2023-07-29T15:04:18.1410481+00:00",
        "completed": true
    },
    {
        "id": 5,
        "title": "Activity 5",
        "dueDate": "2023-07-29T16:04:18.1410485+00:00",
        "completed": false
    },
    {
        "id": 6,
        "title": "Activity 6",
        "dueDate": "2023-07-29T17:04:18.1410489+00:00",
        "completed": true
    },
    {
        "id": 7,
        "title": "Activity 7",
        "dueDate": "2023-07-29T18:04:18.1410492+00:00",
        "completed": false
    },
    {
        "id": 8,
        "title": "Activity 8",
        "dueDate": "2023-07-29T19:04:18.1410495+00:00",
        "completed": true
    },
    {
        "id": 9,
        "title": "Activity 9",
        "dueDate": "2023-07-29T20:04:18.1410497+00:00",
        "completed": false
    },
    {
        "id": 10,
        "title": "Activity 10",
        "dueDate": "2023-07-29T21:04:18.1410502+00:00",
        "completed": true
    },
    {
        "id": 11,
        "title": "Activity 11",
        "dueDate": "2023-07-29T22:04:18.1410505+00:00",
        "completed": false
    },
    {
        "id": 12,
        "title": "Activity 12",
        "dueDate": "2023-07-29T23:04:18.1410508+00:00",
        "completed": true
    },
    {
        "id": 13,
        "title": "Activity 13",
        "dueDate": "2023-07-30T00:04:18.1410511+00:00",
        "completed": false
    },
    {
        "id": 14,
        "title": "Activity 14",
        "dueDate": "2023-07-30T01:04:18.1410514+00:00",
        "completed": true
    },
    {
        "id": 15,
        "title": "Activity 15",
        "dueDate": "2023-07-30T02:04:18.1410517+00:00",
        "completed": false
    },
    {
        "id": 16,
        "title": "Activity 16",
        "dueDate": "2023-07-30T03:04:18.141052+00:00",
        "completed": true
    },
    {
        "id": 17,
        "title": "Activity 17",
        "dueDate": "2023-07-30T04:04:18.1410523+00:00",
        "completed": false
    },
    {
        "id": 18,
        "title": "Activity 18",
        "dueDate": "2023-07-30T05:04:18.1410527+00:00",
        "completed": true
    },
    {
        "id": 19,
        "title": "Activity 19",
        "dueDate": "2023-07-30T06:04:18.1410531+00:00",
        "completed": false
    },
    {
        "id": 20,
        "title": "Activity 20",
        "dueDate": "2023-07-30T07:04:18.1410534+00:00",
        "completed": true
    },
    {
        "id": 21,
        "title": "Activity 21",
        "dueDate": "2023-07-30T08:04:18.1410537+00:00",
        "completed": false
    },
    {
        "id": 22,
        "title": "Activity 22",
        "dueDate": "2023-07-30T09:04:18.141054+00:00",
        "completed": true
    },
    {
        "id": 23,
        "title": "Activity 23",
        "dueDate": "2023-07-30T10:04:18.1410543+00:00",
        "completed": false
    },
    {
        "id": 24,
        "title": "Activity 24",
        "dueDate": "2023-07-30T11:04:18.1410546+00:00",
        "completed": true
    },
    {
        "id": 25,
        "title": "Activity 25",
        "dueDate": "2023-07-30T12:04:18.1410549+00:00",
        "completed": false
    },
    {
        "id": 26,
        "title": "Activity 26",
        "dueDate": "2023-07-30T13:04:18.1410552+00:00",
        "completed": true
    },
    {
        "id": 27,
        "title": "Activity 27",
        "dueDate": "2023-07-30T14:04:18.1410554+00:00",
        "completed": false
    },
    {
        "id": 28,
        "title": "Activity 28",
        "dueDate": "2023-07-30T15:04:18.1410557+00:00",
        "completed": true
    },
    {
        "id": 29,
        "title": "Activity 29",
        "dueDate": "2023-07-30T16:04:18.141056+00:00",
        "completed": false
    },
    {
        "id": 30,
        "title": "Activity 30",
        "dueDate": "2023-07-30T17:04:18.1410563+00:00",
        "completed": true
    }
]
